# Generated by Django 5.0.6 on 2024-05-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extended_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectionToolCertificateDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('reason', models.IntegerField(choices=[(0, 'Добавлено'), (1, 'Изменено'), (2, 'Удалено')], verbose_name='Тип изменения')),
                ('number', models.CharField(max_length=1024, unique=True, verbose_name='№ сертификата')),
                ('date_added_old', models.DateField(verbose_name='Дата внесения в реестр (старое)')),
                ('date_added_new', models.DateField(verbose_name='Дата внесения в реестр (новое)')),
                ('validity_period_old', models.DateField(verbose_name='Срок действия сертификата (старое)')),
                ('validity_period_new', models.DateField(verbose_name='Срок действия сертификата (новое)')),
                ('tool_old', models.CharField(max_length=1024, verbose_name='СЗИ (старое)')),
                ('tool_new', models.CharField(max_length=1024, verbose_name='СЗИ (новое)')),
                ('documents_old', models.TextField(verbose_name='Наименования документов, требованиям которых соответствует средство (старое)')),
                ('documents_new', models.TextField(verbose_name='Наименования документов, требованиям которых соответствует средство (новое)')),
                ('certification_schema_old', models.CharField(max_length=1024, verbose_name='Схема сертификации (старое)')),
                ('certification_schema_new', models.CharField(max_length=1024, verbose_name='Схема сертификации (новое)')),
                ('laboratory_old', models.CharField(max_length=1024, verbose_name='Испытательная лаборатория (старое)')),
                ('laboratory_new', models.CharField(max_length=1024, verbose_name='Испытательная лаборатория (новое)')),
                ('agency_old', models.CharField(max_length=1024, verbose_name='Орган по сертификации (старое)')),
                ('agency_new', models.CharField(max_length=1024, verbose_name='Орган по сертификации (новое)')),
                ('applicant_old', models.CharField(max_length=1024, verbose_name='Заявитель (старое)')),
                ('applicant_new', models.CharField(max_length=1024, verbose_name='Заявитель (новое)')),
                ('requisites_old', models.CharField(max_length=1024, verbose_name='Реквизиты заявителя (индекс, адрес, телефон) (старое)')),
                ('requisites_new', models.CharField(max_length=1024, verbose_name='Реквизиты заявителя (индекс, адрес, телефон) (новое)')),
                ('support_period_old', models.DateField(verbose_name='Информация об окончании срока технической поддержки, полученная от заявителя (старое)')),
                ('support_period_new', models.DateField(verbose_name='Информация об окончании срока технической поддержки, полученная от заявителя (новое)')),
            ],
            options={
                'verbose_name': 'Обновление сертификата СЗИ',
            },
        ),
        migrations.CreateModel(
            name='ProtectionToolCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.CharField(max_length=1024, unique=True, verbose_name='№ сертификата')),
                ('date_added', models.DateField(verbose_name='Дата внесения в реестр')),
                ('validity_period', models.DateField(verbose_name='Срок действия сертификата')),
                ('documents', models.TextField(verbose_name='Наименования документов, требованиям которых соответствует средство')),
                ('certification_schema', models.CharField(max_length=1024, verbose_name='Схема сертификации')),
                ('laboratory', models.CharField(max_length=1024, verbose_name='Испытательная лаборатория')),
                ('agency', models.CharField(max_length=1024, verbose_name='Орган по сертификации')),
                ('applicant', models.CharField(max_length=1024, verbose_name='Заявитель')),
                ('requisites', models.CharField(max_length=1024, verbose_name='Реквизиты заявителя (индекс, адрес, телефон)')),
                ('support_period', models.DateField(verbose_name='Информация об окончании срока технической поддержки, полученная от заявителя')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_by_author', to='extended_user.profile', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сертификат СЗИ',
            },
        ),
    ]
