# Generated by Django 5.0.6 on 2024-05-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protection_certificate', '0002_initial'),
        ('updater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectiontoolcertificatediff',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='updater.version', verbose_name='версия'),
        ),
    ]
