# Generated by Django 5.0.6 on 2024-05-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protection_certificate', '0007_protectiontoolcertificate_support_period_infinity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectiontoolcertificate',
            name='validity_period',
            field=models.DateField(null=True, verbose_name='Срок действия сертификата'),
        ),
    ]
