# Generated by Django 5.0.6 on 2024-06-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protection_certificate', '0010_protectiontoolcertificatediff_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protectiontoolcertificate',
            name='author',
        ),
        migrations.RemoveField(
            model_name='protectiontoolcertificate',
            name='last_editor',
        ),
        migrations.AlterField(
            model_name='protectiontoolcertificate',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='protectiontoolcertificate',
            name='edited',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
