# Generated by Django 5.0.6 on 2024-05-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectionTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=1024, unique=True, verbose_name='Наименование средства')),
            ],
            options={
                'verbose_name': 'Средство защиты информации',
            },
        ),
    ]
