# Generated by Django 5.0.6 on 2024-05-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создано'), (1, 'В обработке'), (3, 'Ошибка'), (2, 'Успех')], default=0, verbose_name='Статус'),
        ),
    ]
