# Generated by Django 5.0.6 on 2024-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_me',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления'),
        ),
    ]
