# Generated by Django 5.0.6 on 2024-05-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('param1', models.IntegerField(verbose_name='Параметр 1')),
                ('param2', models.IntegerField(verbose_name='Параметр 2')),
            ],
            options={
                'verbose_name': 'Тестовый сценарий',
            },
        ),
    ]
